"""Initial schema with yields

Revision ID: 65a6a45ffa5a
Revises: f290aa0fdda9
Create Date: 2026-03-16 09:14:26.319521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a6a45ffa5a'
down_revision: Union[str, Sequence[str], None] = 'f290aa0fdda9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
